trigger:
  branches:
    include:
      - main 
pool:
  vmImage: ubuntu-latest
stages:
- stage: Publish
  jobs:
  - job: Publish
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:   
    - task: Npm@1
      inputs:
        command: publish
        publishRegistry: useFeed
        publishFeed: 'MyXalary/atb'
       